name: cpu_signac_pytorch_pl_mnist_example
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy=1.24.0
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::pytorch-lightning
  - conda-forge::matplotlib
  - signac
  - signac-flow
  - signac-dashboard