[project]
name = "plmnist"
version = "0.0.1"
authors = [
    {name = "Michael Klamkin", email = "klam@isye.gatech.edu"},
    {name = "Brad Crawford", email = "bcrawford39@gatech.edu"}
]

[tool.setuptools.packages.find]
include = ["plmnist*"]